const Constants = {
  GET_FORMS: 'GET_FORMS',
  FORMS_RECEIVED: 'FORMS_RECEIVED',
  ADD_FORM: 'ADD_FORM',
  FORM_ADDED: 'FORM_ADDED',
  GET_FORM: 'GET_FORM',
  FORM_RECEIVED: 'FORM_RECEIVED',
  SAVE_SURVEY: 'SAVE_SURVEY',
  SURVEY_SAVED: 'SURVEY_SAVED'
}

export default Constants;
